### ISSUE TITLE
Select 2

### ISSUE THREAD

**Issue by LucianoRK** [LucianoRK/raiz#9]
Corrigir problema de layout do select 2

**Comment by LucianoRK** [comment]
![image](https://user-images.githubusercontent.com/32466727/72667279-dc5d5c00-39f8-11ea-9fd0-e7bbc16b7f39.png)

**Comment by stavski** [comment]
Corrigido, foi criado uma função no arquivo script.js com o nome selectOne, basta chamar esta função e no select colocar a classe .selectUm
